### ISSUE TITLE
Exception thrown if owner is not defined for an emote

### ISSUE THREAD

**Issue by mknight2059** [probablyjassin/seventv#1]
I have a discord bot that uses this library to find emotes using the 7TV api, and I found that if an emote has no owner, an error is thrown. 

The particular command I have pulls the top 5 hits for emotes and posts them, letting the user choose the correct one. The search term that caused the error was "amogus," and is because this emote has no owner set: https://7tv.app/emotes/60d05e9c67daafaa5f2a47b0.

`An error occurred: 'NoneType' object has no attribute 'get'`

**Comment by probablyjassin** [comment]
Thanks for noticing, sorry that it took so long, but I fixed that issue under release 2.4.1 just now :)
